channels:
  - bioconda
  - conda-forge
dependencies:
  - snakemake-minimal =5.2.4
  - pandoc =2.8
  - python =3.6
  - samtools =1.3
  - sra-tools =2.9.6
  - bowtie =1.2.3
  - homer =4.10
  - deeptools =3.3.1
  - r =3.6.0
  - r-rmarkdown =1.16
  - r-lattice
  - r-rcolorbrewer
  - r-devtools
  - bioconductor-rtracklayer
  - bioconductor-HilbertVis
  - bioconductor-GenomicFeatures
  - bioconductor-ShortRead
  - bioconductor-TxDb.Dmelanogaster.UCSC.dm6.ensGene
  - r-cellranger =1.1.0
